name: Uppdatera Kalender

on:
  schedule:
    - cron: '0 */6 * * *' # Körs automatiskt var 6:e timme
  workflow_dispatch: # Gör att du kan klicka på "Run workflow" manuellt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hämta koden
      uses: actions/checkout@v4

    - name: Sätt upp Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installera nödvändiga bibliotek
      run: |
        python -m pip install --upgrade pip
        pip install requests icalendar pytz gspread google-auth

    - name: Kör Python-skriptet
      env:
        FOGIS_API_KEY: ${{ secrets.FOGIS_API_KEY }}
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: python generator.py

    - name: Spara och ladda upp den nya kalendern
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kalender.ics
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-uppdaterad kalender via FOGIS och Sheets" && git push)
